[package]
name = "yay"
version = "0.1.0"
edition = "2021"

[dependencies]
# gst-plugin-gtk4 = { version = "0.13.0", features = ["dmabuf", "wayland"] }
gstreamer = "0.23.0"
gtk4 = "0.9.0"
libadwaita = "0.7.0"
